name: nextcloud

services:
  nextcloud-db:
    image: ${MARIADB_SERVER}
    container_name: nextcloud_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ${APPDATA}/nextcloud/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nextcloud:
    image: ${NEXTCLOUD_SERVER}
    container_name: nextcloud
    depends_on:
      nextcloud-db:
        condition: service_healthy
    env_file:
      - secrets.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ${APPDATA}/nextcloud/config:/config
      - ${APPDATA}/nextcloud/data:/data
    ports:
      - 4432:443
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
